###

POST http://localhost:8080/member/signup
Content-Type: application/json

{
  "memberEmail": "dan10@gmail.com",
    "memberName": "dan",
    "memberPassword": "1234",
  "dob": "1996-03-21",
  "passwordConfirm": "1234"
}


###
POST http://localhost:8080/member/login
Content-Type: application/json

{
  "memberEmail": "dan10@gmail.com",
  "memberPassword": "1234"
}

###
GET http://localhost:8080/member/auth/myPage
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJkYW4xMEBnbWFpbC5jb20iLCJhdXRoIjoiUk9MRV9VU0VSIiwiZXhwIjoxNjY3MzQ2ODQ3fQ.PhVojAGDFyYWFz2mMX7g0U6-jQBFVWCWSFHVu7CaKm78MgSE-Kn2FRlrBKkUUmJp0-N7kA7rgUAvfPzzOvWg0g



###
PUT http://localhost:8080/auth/boards/7/update
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJkYW4xMEBnbWFpbC5jb20iLCJhdXRoIjoiUk9MRV9VU0VSIiwiZXhwIjoxNjY3MzQwMDUxfQ.k9-g3VnoU6nHi_UdTEJ5C95W3Q1ifPGE7XyJGSZfE2TmdkBoodVSCAK74iOfN5dJsEZCd0SHij3gxUtwY-JvtA

{
  "boardContent": "changed to this, now try to add a comment"
}


###
GET http://localhost:8080/auth/boards/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJkYW4xMEBnbWFpbC5jb20iLCJhdXRoIjoiUk9MRV9VU0VSIiwiZXhwIjoxNjY3MzQ1MDQyfQ.l6EWGx6aFoihhfrhdNlbAc-OlgHf_GaC598xbdi0FeKXjLarTiIJN394gpKn_ijhbHscg2BJMxVHsocPJtaWdQ


{
  "boardContent": "changed to this, now try to add a comment"
}


###

POST http://localhost:8080/auth/comments/6/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJkYW4xMEBnbWFpbC5jb20iLCJhdXRoIjoiUk9MRV9VU0VSIiwiZXhwIjoxNjY3MzQ1MDQyfQ.l6EWGx6aFoihhfrhdNlbAc-OlgHf_GaC598xbdi0FeKXjLarTiIJN394gpKn_ijhbHscg2BJMxVHsocPJtaWdQ

{
  "commentContent": "하하잉"
}


###

GET http://localhost:8080/auth/boards/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJkYW4xQGdtYWlsLmNvbSIsImF1dGgiOiJST0xFX1VTRVIiLCJleHAiOjE2NjcyNTEwNDd9.jB2AFIeOCHvwZPntKu8M8-rld1DZEmeQ4dBegASxHf9KouqLZ6uX5qoDy68W55FsaH7gTPwVeyBjiUmXFAzVkw

###

DELETE http://localhost:8080/auth/boards/8/delete
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJkYW4xMEBnbWFpbC5jb20iLCJhdXRoIjoiUk9MRV9VU0VSIiwiZXhwIjoxNjY3MzM1Nzg3fQ.uIzyS4OfQcOvHw0jvWy9jEaFMpR9QCypf1Ac1v4yyCLhJkNbBnpZ-nIazxfGAPNUKf59YsImDrnhco2plVI4_A

###

PUT http://localhost:8080/auth/comments/4/update
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJkYW45QGdtYWlsLmNvbSIsImF1dGgiOiJST0xFX1VTRVIiLCJleHAiOjE2NjczMjQyNTN9._NAgdk6pS01NmeXdgmdub5a1nmwjrOx13XrTReNU4IEJ_fW95BZMcKomCEfHj7E9RrRXP7NzmyJW_zb2Nu2VWg

{
  "commentContent": "boooo"
}

###


DELETE http://localhost:8080/auth/comments/4/delete
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJkYW45QGdtYWlsLmNvbSIsImF1dGgiOiJST0xFX1VTRVIiLCJleHAiOjE2NjczMjQyNTN9._NAgdk6pS01NmeXdgmdub5a1nmwjrOx13XrTReNU4IEJ_fW95BZMcKomCEfHj7E9RrRXP7NzmyJW_zb2Nu2VWg

###

GET http://localhost:8080/auth/comments
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJkYW5AZ21haWwuY29tIiwiYXV0aCI6IlJPTEVfVVNFUiIsImV4cCI6MTY2NzE3ODc0OH0.3NSRiMqKrSJZvwJIkASvWlcQOCl40Kw46-uMJowHYle_h6WAA1VDgfmwHYzJCxrns8O146h20S0-ACMnZUfGqA


###

POST http://localhost:8080/auth/3/heart
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJkYW4xQGdtYWlsLmNvbSIsImF1dGgiOiJST0xFX1VTRVIiLCJleHAiOjE2NjcxODUxMDl9.jmXO1Yga6Jgu0AdzqRbS1ooAAYso8h-Mpb-Vqg0g9TnzE3ocfmcJrRBWyT8-xm5xvTueO4ycuN9YsEzAMDcGEg

###

GET http://localhost:8080/member/mypage
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJkYW4xQGdtYWlsLmNvbSIsImF1dGgiOiJST0xFX1VTRVIiLCJleHAiOjE2NjcxODUxMDl9.jmXO1Yga6Jgu0AdzqRbS1ooAAYso8h-Mpb-Vqg0g9TnzE3ocfmcJrRBWyT8-xm5xvTueO4ycuN9YsEzAMDcGEg
