###

POST http://localhost:8080/member/signup
Content-Type: application/json

{
  "memberEmail": "dan@gmail.com",
    "memberName": "dan",
    "memberPassword": "1234",
  "passwordConfirm": "1234"
}


###
POST http://localhost:8080/member/login
Content-Type: application/json

{
  "memberEmail": "dan@gmail.com",
  "memberPassword": "1234"
}

###

POST http://localhost:8080/auth/boards/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJkYW5AZ21haWwuY29tIiwiYXV0aCI6IlJPTEVfVVNFUiIsImV4cCI6MTY2NzE0NzE0M30.oUQuMv-3YGejUpOGp2UTf2Tqsv_eX0yd-4xRkWHgoeJuiECA93zXwdKmF47YOuYPqa7CWyFyLcQ4QBlienrbFw


{
  "boardContent": "졸려려려ㅕㄹ"
}


###

PUT http://localhost:8080/auth/boards/7/update
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJkYW5AZ21haWwuY29tIiwiYXV0aCI6IlJPTEVfVVNFUiIsImV4cCI6MTY2NzE0NzE0M30.oUQuMv-3YGejUpOGp2UTf2Tqsv_eX0yd-4xRkWHgoeJuiECA93zXwdKmF47YOuYPqa7CWyFyLcQ4QBlienrbFw


{
  "boardContent": "자라"
}


###
GET http://localhost:8080/auth/boards/
Content-Type: application/json
Authorization: eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZGFtMkBnbWFpbC5jb20iLCJhdXRoIjoiUk9MRV9VU0VSIiwiZXhwIjoxNjY3MDc3MjQ0fQ.jo3YIJ-qHGKd2ms7Es5Tj_Sl4gqjVDaKghMojDxAMhof842nJtxAtV8YurnI3IzXGzwRtoI0IC9yzFCKFr1JyQ




###

POST http://localhost:8080/auth/comments/6/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJkYW5AZ21haWwuY29tIiwiYXV0aCI6IlJPTEVfVVNFUiIsImV4cCI6MTY2NzE0NzQ4Nn0.dDq3lzwl0s3xBnUo55hS_vDs4GOFAT7U0UrsKhYkS1a3iZh-T7qQXwhvhiQv3xAMaNhMA4yLKD6nr-QCLexBOA

{
  "commentContent": "testing"
}



###

GET http://localhost:8080/boards/5
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJkYW5AZ21haWwuY29tIiwiYXV0aCI6IlJPTEVfVVNFUiIsImV4cCI6MTY2NzEyMjIwNX0.GM-DWBPs6Bmui0VbfgLWFrmQKpYnuZqGlmtFmGsOdbmWw6_B2iwGf4NuM_BAw6vOAayXwRifMzH7rpiO0mPbRg

###


DELETE http://localhost:8080/auth/boards/7/delete
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJkYW5AZ21haWwuY29tIiwiYXV0aCI6IlJPTEVfVVNFUiIsImV4cCI6MTY2NzE0NzE0M30.oUQuMv-3YGejUpOGp2UTf2Tqsv_eX0yd-4xRkWHgoeJuiECA93zXwdKmF47YOuYPqa7CWyFyLcQ4QBlienrbFw


###






PUT http://localhost:8080/auth/comments/5/update
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJkYW5AZ21haWwuY29tIiwiYXV0aCI6IlJPTEVfVVNFUiIsImV4cCI6MTY2NzE0NzQ4Nn0.dDq3lzwl0s3xBnUo55hS_vDs4GOFAT7U0UrsKhYkS1a3iZh-T7qQXwhvhiQv3xAMaNhMA4yLKD6nr-QCLexBOA

{
  "modifiedComment": "hihihihii"
}

###


DELETE http://localhost:8080/auth/comments/5/delete
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJkYW5AZ21haWwuY29tIiwiYXV0aCI6IlJPTEVfVVNFUiIsImV4cCI6MTY2NzE0NzQ4Nn0.dDq3lzwl0s3xBnUo55hS_vDs4GOFAT7U0UrsKhYkS1a3iZh-T7qQXwhvhiQv3xAMaNhMA4yLKD6nr-QCLexBOA

###

GET http://localhost:8080/auth/comments
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZGFtMkBnbWFpbC5jb20iLCJhdXRoIjoiUk9MRV9VU0VSIiwiZXhwIjoxNjY3MTI1ODU2fQ.bQvzdjZK3FCNkfkaE1RJXNqIZFEegvV8rK19nI_er-n_K4WgXnktAxgHSY6ocvPvReUObRaqOoWbDQJi6AWqzg


