###

POST http://localhost:8080/member/signup
Content-Type: application/json

{
  "memberEmail": "dan@gmail.com",
    "memberName": "dan",
    "memberPassword": "1234",
  "passwordConfirm": "1234"
}


###
POST http://localhost:8080/member/login
Content-Type: application/json

{
  "memberEmail": "dan@gmail.com",
  "memberPassword": "1234"
}

###

POST http://localhost:8080/auth/boards/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJkYW5AZ21haWwuY29tIiwiYXV0aCI6IlJPTEVfVVNFUiIsImV4cCI6MTY2NzE3MDA4MH0.alLolD8C9hFcBYd-VgrnOGSUOFDkQuDKIuSWyp1DrHhVdFRffIRZ0QonMxtA8io-nNebp59IqdlNXBRtUEHZaQ


{
  "boardContent": "this is going second."
}


###

PUT http://localhost:8080/auth/boards/6/update
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJkYW5AZ21haWwuY29tIiwiYXV0aCI6IlJPTEVfVVNFUiIsImV4cCI6MTY2NzE3MDA4MH0.alLolD8C9hFcBYd-VgrnOGSUOFDkQuDKIuSWyp1DrHhVdFRffIRZ0QonMxtA8io-nNebp59IqdlNXBRtUEHZaQ


{
  "boardContent": "changed to this, now try to add a comment"
}


###
GET http://localhost:8080/auth/boards/5
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJkYW5AZ21haWwuY29tIiwiYXV0aCI6IlJPTEVfVVNFUiIsImV4cCI6MTY2NzE3MDA4MH0.alLolD8C9hFcBYd-VgrnOGSUOFDkQuDKIuSWyp1DrHhVdFRffIRZ0QonMxtA8io-nNebp59IqdlNXBRtUEHZaQ




###

POST http://localhost:8080/auth/comments/5/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJkYW5AZ21haWwuY29tIiwiYXV0aCI6IlJPTEVfVVNFUiIsImV4cCI6MTY2NzE2ODM3Nn0.QZTQVdMM51Ip4iAN0cTjrwCVbHILQm6jQmtrMSWX0PCd_jT-bZjz9MaLPK-_sm5i2XDwgbSAoCPNUedlG3xhYg

{
  "commentContent": "하하잉"
}


###

GET http://localhost:8080/auth/boards/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJkYW5AZ21haWwuY29tIiwiYXV0aCI6IlJPTEVfVVNFUiIsImV4cCI6MTY2NzE2ODM3Nn0.QZTQVdMM51Ip4iAN0cTjrwCVbHILQm6jQmtrMSWX0PCd_jT-bZjz9MaLPK-_sm5i2XDwgbSAoCPNUedlG3xhYg

###

DELETE http://localhost:8080/auth/boards/6/delete
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJkYW5AZ21haWwuY29tIiwiYXV0aCI6IlJPTEVfVVNFUiIsImV4cCI6MTY2NzE2ODM3Nn0.QZTQVdMM51Ip4iAN0cTjrwCVbHILQm6jQmtrMSWX0PCd_jT-bZjz9MaLPK-_sm5i2XDwgbSAoCPNUedlG3xhYg

###

PUT http://localhost:8080/auth/comments/12/update
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJkYW5AZ21haWwuY29tIiwiYXV0aCI6IlJPTEVfVVNFUiIsImV4cCI6MTY2NzE3MDA4MH0.alLolD8C9hFcBYd-VgrnOGSUOFDkQuDKIuSWyp1DrHhVdFRffIRZ0QonMxtA8io-nNebp59IqdlNXBRtUEHZaQ

{
  "modifiedComment": "ㅗ디ㅣㅐ"
}

###


DELETE http://localhost:8080/auth/comments/12/delete
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJkYW5AZ21haWwuY29tIiwiYXV0aCI6IlJPTEVfVVNFUiIsImV4cCI6MTY2NzE3ODc0OH0.3NSRiMqKrSJZvwJIkASvWlcQOCl40Kw46-uMJowHYle_h6WAA1VDgfmwHYzJCxrns8O146h20S0-ACMnZUfGqA

###

GET http://localhost:8080/auth/comments
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJkYW5AZ21haWwuY29tIiwiYXV0aCI6IlJPTEVfVVNFUiIsImV4cCI6MTY2NzE3ODc0OH0.3NSRiMqKrSJZvwJIkASvWlcQOCl40Kw46-uMJowHYle_h6WAA1VDgfmwHYzJCxrns8O146h20S0-ACMnZUfGqA


